# Generated by Django 5.2.4 on 2025-08-17 14:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('course', '0001_initial'), ('course', '0002_remove_course_enroll_code_course_description_and_more'), ('course', '0003_rename_line_user_course_owner_and_more'), ('course', '0004_course_course_state_course_updated_at_and_more'), ('course', '0005_alter_course_options_alter_course_course_state_and_more'), ('course', '0006_alter_course_created_at_alter_course_updated_at_and_more'), ('course', '0007_alter_course_created_at_alter_course_updated_at_and_more'), ('course', '0008_alter_course_options_and_more'), ('course', '0009_coursetimeslot_note_studenttask'), ('course', '0010_remove_note_course_remove_note_owner_and_more')]

    initial = True

    dependencies = [
        ('user', '0002_lineprofile_google_access_token_and_more'),
        ('user', '0003_alter_lineprofile_options_alter_registration_options_and_more'),
        ('user', '0006_alter_lineprofile_options_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('gc_course_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_courses', to='user.lineprofile')),
                ('description', models.TextField(blank=True)),
                ('enrollment_code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('course_state', models.CharField(choices=[('ACTIVE', '啟用'), ('ARCHIVED', '封存'), ('PROVISIONED', '佈建中'), ('DECLINED', '已拒絕'), ('SUSPENDED', '暫停')], db_index=True, default='ACTIVE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('gc_homework_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('gc_course_id', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(choices=[('PUBLISHED', '已發布'), ('DRAFT', '草稿'), ('DELETED', '已刪除')], db_index=True, default='PUBLISHED', max_length=20)),
                ('work_type', models.CharField(choices=[('ASSIGNMENT', '作業'), ('SHORT_ANSWER_QUESTION', '簡答題'), ('MULTIPLE_CHOICE_QUESTION', '選擇題'), ('COURSE_WORK_TYPE_UNSPECIFIED', '未指定')], default='ASSIGNMENT', max_length=30)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('max_points', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='course.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_homeworks', to='user.lineprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['owner', 'course_state'], name='course_cour_owner_i_1ba135_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at', 'course_state'], name='course_cour_created_8841d5_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name', 'course_state'], name='course_cour_name_b9910e_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['course', 'state'], name='course_home_course__9f9fad_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['owner', 'due_date'], name='course_home_owner_i_bb0bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['gc_course_id', 'state'], name='course_home_gc_cour_40d36b_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['due_date', 'state'], name='course_home_due_dat_65ddfa_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['created_at', 'state'], name='course_home_created_004898_idx'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='course_cour_owner_i_1ba135_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='course_cour_created_8841d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='course_cour_name_b9910e_idx',
        ),
        migrations.RemoveIndex(
            model_name='homework',
            name='course_home_course__9f9fad_idx',
        ),
        migrations.RemoveIndex(
            model_name='homework',
            name='course_home_owner_i_bb0bcd_idx',
        ),
        migrations.RemoveIndex(
            model_name='homework',
            name='course_home_gc_cour_40d36b_idx',
        ),
        migrations.RemoveIndex(
            model_name='homework',
            name='course_home_due_dat_65ddfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='homework',
            name='course_home_created_004898_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_state',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='gc_course_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lineprofile'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='gc_course_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homework',
            name='gc_homework_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='max_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lineprofile'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='state',
            field=models.CharField(default='PUBLISHED', max_length=20),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homework',
            name='work_type',
            field=models.CharField(default='ASSIGNMENT', max_length=20),
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='course.course')),
            ],
            options={
                'indexes': [models.Index(fields=['day_of_week', 'start_time', 'end_time'], name='course_cour_day_of__5f843b_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('classified_by', models.CharField(default='none', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lineprofile')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='course_stud_created_a0add2_idx')],
            },
        ),
    ]
