# Generated by Django 5.2.4 on 2025-07-28 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_lineprofile_google_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('section', models.CharField(blank=True, max_length=50)),
                ('gc_course_id', models.CharField(max_length=50, unique=True)),
                ('enroll_code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lineprofile')),
            ],
        ),
    ]
