# Generated by Django 5.2.4 on 2025-07-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_enroll_code_course_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='line_user',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='gc_course_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
