# Generated by Django 5.2.4 on 2025-08-05 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_rename_line_user_course_owner_and_more'),
        ('user', '0002_lineprofile_google_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_state',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='gc_course_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('gc_homework_id', models.CharField(max_length=100, unique=True)),
                ('gc_course_id', models.CharField(max_length=100)),
                ('state', models.CharField(default='PUBLISHED', max_length=20)),
                ('work_type', models.CharField(default='ASSIGNMENT', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('max_points', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lineprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
