# Generated by Django 5.2.4 on 2025-08-07 08:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_course_state_course_updated_at_and_more'),
        ('user', '0003_alter_lineprofile_options_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='course',
            name='course_state',
            field=models.CharField(choices=[('ACTIVE', '啟用'), ('ARCHIVED', '封存'), ('PROVISIONED', '佈建中'), ('DECLINED', '已拒絕'), ('SUSPENDED', '暫停')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment_code',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='gc_course_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_courses', to='user.lineprofile'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='course.course'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='gc_course_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='homework',
            name='gc_homework_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='max_points',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='homework',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_homeworks', to='user.lineprofile'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='state',
            field=models.CharField(choices=[('PUBLISHED', '已發布'), ('DRAFT', '草稿'), ('DELETED', '已刪除')], db_index=True, default='PUBLISHED', max_length=20),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='homework',
            name='work_type',
            field=models.CharField(choices=[('ASSIGNMENT', '作業'), ('SHORT_ANSWER_QUESTION', '簡答題'), ('MULTIPLE_CHOICE_QUESTION', '選擇題'), ('COURSE_WORK_TYPE_UNSPECIFIED', '未指定')], default='ASSIGNMENT', max_length=30),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['owner', 'course_state'], name='course_cour_owner_i_1ba135_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['created_at', 'course_state'], name='course_cour_created_8841d5_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['name', 'course_state'], name='course_cour_name_b9910e_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['course', 'state'], name='course_home_course__9f9fad_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['owner', 'due_date'], name='course_home_owner_i_bb0bcd_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['gc_course_id', 'state'], name='course_home_gc_cour_40d36b_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['due_date', 'state'], name='course_home_due_dat_65ddfa_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['created_at', 'state'], name='course_home_created_004898_idx'),
        ),
    ]
