# Generated by Django 5.2.4 on 2025-08-07 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_created_at_alter_course_updated_at_and_more'),
        ('user', '0006_alter_lineprofile_options_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='course_cour_owner_i_1ba135_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='course_cour_created_8841d5_idx',
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='course_cour_name_b9910e_idx',
        ),
        migrations.RemoveIndex(
            model_name='homework',
            name='course_home_course__9f9fad_idx',
        ),
        migrations.RemoveIndex(
            model_name='homework',
            name='course_home_owner_i_bb0bcd_idx',
        ),
        migrations.RemoveIndex(
            model_name='homework',
            name='course_home_gc_cour_40d36b_idx',
        ),
        migrations.RemoveIndex(
            model_name='homework',
            name='course_home_due_dat_65ddfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='homework',
            name='course_home_created_004898_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_state',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='enrollment_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='gc_course_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lineprofile'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='gc_course_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homework',
            name='gc_homework_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='max_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homework',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lineprofile'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='state',
            field=models.CharField(default='PUBLISHED', max_length=20),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='homework',
            name='work_type',
            field=models.CharField(default='ASSIGNMENT', max_length=20),
        ),
    ]
