# Generated by Django 5.2.4 on 2025-08-15 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_course_options_and_more'),
        ('user', '0006_alter_lineprofile_options_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='course.course')),
            ],
            options={
                'indexes': [models.Index(fields=['weekday', 'start_time', 'end_time'], name='course_cour_weekday_9ab45d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('image_url', models.CharField(blank=True, max_length=500)),
                ('at_time', models.DateTimeField(blank=True, null=True)),
                ('gc_course_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lineprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'created_at'], name='course_note_owner_i_cf55b8_idx'), models.Index(fields=['gc_course_id'], name='course_note_gc_cour_a6670e_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('at_time', models.DateTimeField(blank=True, null=True)),
                ('gc_course_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lineprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'created_at'], name='course_stud_owner_i_be57c4_idx'), models.Index(fields=['gc_course_id'], name='course_stud_gc_cour_565f2a_idx')],
            },
        ),
    ]
