# Generated by Django 5.2.4 on 2025-08-15 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_coursetimeslot_note_studenttask'),
        ('user', '0006_alter_lineprofile_options_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='course',
        ),
        migrations.RemoveField(
            model_name='note',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='studenttask',
            name='course',
        ),
        migrations.RemoveField(
            model_name='studenttask',
            name='owner',
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='course.course')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('classified_by', models.CharField(default='none', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.lineprofile')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CourseTimeSlot',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='StudentTask',
        ),
        migrations.AddIndex(
            model_name='courseschedule',
            index=models.Index(fields=['day_of_week', 'start_time', 'end_time'], name='course_cour_day_of__5f843b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['created_at'], name='course_stud_created_a0add2_idx'),
        ),
    ]
