# Generated by Django 5.2.4 on 2025-08-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_squashed_0010_remove_note_course_remove_note_owner_and_more'),
        ('user', '0006_alter_lineprofile_options_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['course', 'due_date'], name='course_home_course__914844_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['owner', 'state'], name='course_home_owner_i_b05812_idx'),
        ),
    ]
