# Generated by Django 5.2.4 on 2025-08-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_homework_course_home_course__914844_idx_and_more'),
        ('user', '0006_alter_lineprofile_options_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentnote',
            name='note_type',
            field=models.CharField(choices=[('class', '課堂筆記'), ('homework', '作業筆記'), ('review', '復習筆記'), ('exam', '考試筆記'), ('personal', '個人想法'), ('summary', '重點整理'), ('question', '問題筆記'), ('research', '資料搜集'), ('other', '其他')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('normal', '普通'), ('high', '高')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='tags',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['note_type'], name='course_stud_note_ty_7ad21b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['priority'], name='course_stud_priorit_f85c76_idx'),
        ),
    ]
