# Generated by Django 5.2.4 on 2025-08-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_add_note_classification_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='studentnote',
            name='course_stud_note_ty_7ad21b_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentnote',
            name='course_stud_priorit_f85c76_idx',
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='note_type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='priority',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
