# Generated by Django 5.2.4 on 2025-09-13 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('course', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='studentnote',
            name='content',
            field=models.TextField(blank=True, help_text='支援 HTML 格式的筆記內容'),
        ),
        migrations.AddField(
            model_name='studentnote',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='user.lineprofile'),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentnote',
            name='text',
            field=models.TextField(blank=True, help_text='純文字內容（向後相容）'),
        ),
        migrations.AddIndex(
            model_name='studentnote',
            index=models.Index(fields=['author', 'course'], name='course_stud_author__1239b7_idx'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_file_attachments', to='contenttypes.contenttype'),
        ),
    ]
