# Generated by Django 5.2.4 on 2025-09-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0004_customcategory_customtodoitem'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('snippet', models.TextField(blank=True)),
                ('embedding', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentRecItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('position', models.IntegerField()),
                ('rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api_v2.assignmentrecommendation')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.learningresource')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
