# Generated by Django 4.2.24 on 2025-10-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeBindCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128, unique=True)),
                ('course_id', models.CharField(max_length=100)),
                ('course_name', models.CharField(blank=True, default='', max_length=200)),
                ('enrollment_code', models.CharField(blank=True, default='', max_length=50)),
                ('created_by_line_user_id', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code_hash'], name='line_bot_on_code_ha_440712_idx'), models.Index(fields=['expires_at'], name='line_bot_on_expires_98b684_idx')],
            },
        ),
        migrations.CreateModel(
            name='HomeworkStatisticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(help_text='教師的LINE用戶ID', max_length=50)),
                ('course_id', models.CharField(help_text='Google Classroom課程ID', max_length=100)),
                ('coursework_id', models.CharField(help_text='Google Classroom作業ID', max_length=100)),
                ('course_name', models.CharField(default='', help_text='課程名稱', max_length=200)),
                ('homework_title', models.CharField(default='', help_text='作業標題', max_length=200)),
                ('total_students', models.IntegerField(default=0)),
                ('submitted_count', models.IntegerField(default=0)),
                ('unsubmitted_count', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('unsubmitted_students', models.JSONField(default=list, help_text='缺交學生列表，包含name, userId, emailAddress')),
                ('status_counts', models.JSONField(default=dict, help_text='各種狀態的數量統計')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='資料過期時間（預設1小時）')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['line_user_id', 'created_at'], name='line_bot_ho_line_us_1a5563_idx'), models.Index(fields=['course_id', 'coursework_id'], name='line_bot_ho_course__966650_idx'), models.Index(fields=['expires_at'], name='line_bot_ho_expires_7b8ed9_idx')],
            },
        ),
        migrations.CreateModel(
            name='GroupBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=64, unique=True)),
                ('course_id', models.CharField(max_length=100)),
                ('bound_by_line_user_id', models.CharField(max_length=50)),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['group_id'], name='line_bot_gr_group_i_a7793b_idx'), models.Index(fields=['course_id'], name='line_bot_gr_course__75e193_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=50)),
                ('message_type', models.CharField(choices=[('user', '用戶訊息'), ('bot', 'Bot回應'), ('system', '系統訊息')], max_length=10)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['line_user_id', 'created_at'], name='line_bot_co_line_us_740cc5_idx'), models.Index(fields=['message_type'], name='line_bot_co_message_db37af_idx'), models.Index(fields=['intent'], name='line_bot_co_intent_bad04c_idx')],
            },
        ),
    ]
