# Generated by Django 4.2.24 on 2025-10-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineprofile',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='用戶偏好設定和其他擴充資料'),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='role',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
