# Generated by Django 5.2.4 on 2025-08-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=64, unique=True)),
                ('course_id', models.CharField(max_length=100)),
                ('bound_by_line_user_id', models.CharField(max_length=50)),
                ('bound_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['group_id'], name='line_bot_gr_group_i_a7793b_idx'), models.Index(fields=['course_id'], name='line_bot_gr_course__75e193_idx')],
            },
        ),
        migrations.CreateModel(
            name='OneTimeBindCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128, unique=True)),
                ('course_id', models.CharField(max_length=100)),
                ('created_by_line_user_id', models.CharField(max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code_hash'], name='line_bot_on_code_ha_440712_idx'), models.Index(fields=['expires_at'], name='line_bot_on_expires_98b684_idx')],
            },
        ),
    ]
