# Generated by Django 5.2.4 on 2025-08-28 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=50)),
                ('message_type', models.CharField(choices=[('user', '用戶訊息'), ('bot', 'Bot回應'), ('system', '系統訊息')], max_length=10)),
                ('content', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['line_user_id', 'created_at'], name='line_bot_co_line_us_740cc5_idx'), models.Index(fields=['message_type'], name='line_bot_co_message_db37af_idx'), models.Index(fields=['intent'], name='line_bot_co_intent_bad04c_idx')],
            },
        ),
    ]
