# Generated by Django 5.2.4 on 2025-08-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0002_conversationmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkStatisticsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(help_text='教師的LINE用戶ID', max_length=50)),
                ('course_id', models.CharField(help_text='Google Classroom課程ID', max_length=100)),
                ('coursework_id', models.CharField(help_text='Google Classroom作業ID', max_length=100)),
                ('course_name', models.CharField(default='', help_text='課程名稱', max_length=200)),
                ('homework_title', models.CharField(default='', help_text='作業標題', max_length=200)),
                ('total_students', models.IntegerField(default=0)),
                ('submitted_count', models.IntegerField(default=0)),
                ('unsubmitted_count', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('unsubmitted_students', models.JSONField(default=list, help_text='缺交學生列表，包含name, userId, emailAddress')),
                ('status_counts', models.JSONField(default=dict, help_text='各種狀態的數量統計')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='資料過期時間（預設1小時）')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['line_user_id', 'created_at'], name='line_bot_ho_line_us_1a5563_idx'), models.Index(fields=['course_id', 'coursework_id'], name='line_bot_ho_course__966650_idx'), models.Index(fields=['expires_at'], name='line_bot_ho_expires_7b8ed9_idx')],
            },
        ),
    ]
