# Generated by Django 5.2.4 on 2025-08-30 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0003_homeworkstatisticscache'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimebindcode',
            name='course_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='onetimebindcode',
            name='enrollment_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
