# Generated by Django 5.2.4 on 2025-08-07 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_lineprofile_google_access_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='role',
            field=models.CharField(choices=[('teacher', '教師'), ('student', '學生')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='line_user_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('teacher', '教師'), ('student', '學生')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='lineprofile',
            index=models.Index(fields=['role', 'created_at'], name='user_linepr_role_f68815_idx'),
        ),
        migrations.AddIndex(
            model_name='lineprofile',
            index=models.Index(fields=['email', 'role'], name='user_linepr_email_c877a2_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['line_user_id', 'created_at'], name='user_regist_line_us_d0570e_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['role', 'created_at'], name='user_regist_role_7f9c8e_idx'),
        ),
    ]
