# Generated by Django 5.2.4 on 2025-08-07 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_lineprofile_options_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
