# Generated by Django 5.2.4 on 2025-08-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_lineprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='lineprofile',
            name='user_linepr_role_f68815_idx',
        ),
        migrations.RemoveIndex(
            model_name='lineprofile',
            name='user_linepr_email_c877a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='user_regist_line_us_d0570e_idx',
        ),
        migrations.RemoveIndex(
            model_name='registration',
            name='user_regist_role_7f9c8e_idx',
        ),
        migrations.RemoveField(
            model_name='lineprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lineprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='google_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lineprofile',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='line_user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.CharField(max_length=10),
        ),
    ]
