# Generated by Django 4.2.24 on 2025-10-02 16:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('instructor', models.CharField(blank=True, max_length=100, null=True)),
                ('classroom', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(default='#8b5cf6', max_length=20)),
                ('is_google_classroom', models.BooleanField(default=False)),
                ('google_classroom_id', models.CharField(blank=True, max_length=100, null=True)),
                ('google_classroom_url', models.URLField(blank=True, help_text='Google Classroom 課程連結', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_v2', to='user.lineprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, default='clipboard', max_length=30)),
                ('color', models.CharField(blank=True, default='#3b82f6', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_categories', to='user.lineprofile')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('snippet', models.TextField(blank=True)),
                ('embedding', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_user_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'api_v2_userprofile',
                'ordering': ['-last_active'],
            },
        ),
        migrations.CreateModel(
            name='NoteV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_deprecated', to='api_v2.coursev2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_v2_deprecated', to='user.lineprofile')),
            ],
            options={
                'db_table': 'api_v2_notev2',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_v2_file_attachments', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'api_v2_fileattachment',
            },
        ),
        migrations.CreateModel(
            name='ExamV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('exam_date', models.DateTimeField()),
                ('notification_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.IntegerField(help_text='考試時長（分鐘）')),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('midterm', '期中考'), ('final', '期末考'), ('quiz', '小考'), ('other', '其他')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待考'), ('completed', '已完成'), ('overdue', '已結束')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='api_v2.coursev2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='user.lineprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTodoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('overdue', 'overdue')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='api_v2.customcategory')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_todos', to='api_v2.coursev2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_todos', to='user.lineprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentV2',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('notification_time', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('assignment', '作業'), ('project', '專案'), ('reading', '閱讀'), ('other', '其他')], default='assignment', max_length=20)),
                ('status', models.CharField(choices=[('pending', '待完成'), ('completed', '已完成'), ('overdue', '已逾期')], default='pending', max_length=20)),
                ('google_coursework_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('google_classroom_url', models.URLField(blank=True, help_text='Google Classroom 作業連結', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api_v2.coursev2')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_v2', to='user.lineprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_user_id', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('not_started', '未開始'), ('in_progress', '進行中'), ('completed', '已完成'), ('submitted', '已提交'), ('graded', '已評分')], default='not_started', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, help_text='進度百分比 (0-100)')),
                ('notes', models.TextField(blank=True, help_text='用戶備註')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_records', to='api_v2.assignmentv2')),
            ],
            options={
                'db_table': 'api_v2_assignmentstatus',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentRecItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('position', models.IntegerField()),
                ('rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api_v2.assignmentrecommendation')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v2.learningresource')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='CourseScheduleV2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('schedule_source', models.CharField(choices=[('manual', '手動輸入'), ('imported', '匯入資料'), ('inferred', '推測時間')], default='manual', max_length=20)),
                ('is_default_schedule', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api_v2.coursev2')),
            ],
            options={
                'indexes': [models.Index(fields=['day_of_week', 'start_time', 'end_time'], name='api_v2_cour_day_of__76b5eb_idx'), models.Index(fields=['course', 'schedule_source'], name='api_v2_cour_course__370564_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='assignmentv2',
            index=models.Index(fields=['google_coursework_id'], name='api_v2_assi_google__6f42e7_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentv2',
            index=models.Index(fields=['user', 'course'], name='api_v2_assi_user_id_a5f710_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentstatus',
            unique_together={('line_user_id', 'assignment')},
        ),
    ]
