# Generated by Django 4.2.24 on 2025-10-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignmentv2',
            index=models.Index(fields=['user', 'status', 'due_date'], name='api_v2_assi_user_id_01bb6c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentv2',
            index=models.Index(fields=['course', 'due_date'], name='api_v2_assi_course__72f7f8_idx'),
        ),
        migrations.AddIndex(
            model_name='coursev2',
            index=models.Index(fields=['user', 'created_at'], name='api_v2_cour_user_id_e97571_idx'),
        ),
        migrations.AddIndex(
            model_name='coursev2',
            index=models.Index(fields=['user', 'is_google_classroom'], name='api_v2_cour_user_id_5e5891_idx'),
        ),
        migrations.AddIndex(
            model_name='examv2',
            index=models.Index(fields=['user', 'status', 'exam_date'], name='api_v2_exam_user_id_1680f2_idx'),
        ),
        migrations.AddIndex(
            model_name='examv2',
            index=models.Index(fields=['course', 'exam_date'], name='api_v2_exam_course__bd3bf0_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentv2',
            constraint=models.UniqueConstraint(condition=models.Q(('google_coursework_id__isnull', False)), fields=('user', 'google_coursework_id'), name='unique_user_google_coursework'),
        ),
        migrations.AddConstraint(
            model_name='coursev2',
            constraint=models.UniqueConstraint(condition=models.Q(('google_classroom_id__isnull', False)), fields=('user', 'google_classroom_id'), name='unique_user_google_classroom'),
        ),
    ]
