# Generated by Django 5.2.4 on 2025-09-13 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0002_alter_fileattachment_content_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notev2',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_v2_file_attachments', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='notev2',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_deprecated', to='api_v2.coursev2'),
        ),
        migrations.AlterField(
            model_name='notev2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_v2_deprecated', to='user.lineprofile'),
        ),
        migrations.AlterModelTable(
            name='fileattachment',
            table='api_v2_fileattachment',
        ),
        migrations.AlterModelTable(
            name='notev2',
            table='api_v2_notev2',
        ),
    ]
