# Generated by Django 4.2.24 on 2025-10-04 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0002_assignmentv2_api_v2_assi_user_id_01bb6c_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
