@startuml
actor User
participant "ClassroomAI " as System
database "資料庫" as DB

User -> System : 開啟待辦事項事項介面
User -> System : 點選「新增待辦事項」
User -> System : 輸入待辦事項名稱/時間/地點/關聯課程
User -> System : 選擇結束時間/通知時間 
User -> System : 確認送出

System -> System : 驗證內容合法性
alt 驗證失敗
    System -> User : 顯示新增失敗訊息
else 驗證成功
    System -> DB : 儲存待辦事項資料
    DB -> System : 儲存成功
    System -> User : 顯示新增成功訊息

end
@enduml
