@startuml
actor 使用者
participant ClassroomAI as System
database 資料庫 as DB


使用者 -> System: 開啟待辦事項頁面
System -> DB: 查詢待辦事項資料
DB -> System: 傳回待辦事項資料
System -> 使用者: 顯示待辦事項資料

使用者 -> System: 點擊欲刪除之待辦事項
使用者 -> System: 按下刪除按鈕

System -> DB: 刪除待辦事項
DB -> System: 刪除成功
System -> 使用者: 通知刪除成功
@enduml
